### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by gaje** [nodesource/homebrew-nsolid#7]
When installing via brew, i'm getting a SHA256 mismatch error:
```
➜ brew install nsolid-console
==> Installing nsolid-console from nodesource/nsolid
==> Downloading https://s3-us-west-2.amazonaws.com/nodesource-public-downloads/4.3.0/artifacts/bundles/nsolid-bundle-v4
Already downloaded: /Users/ben1231/Library/Caches/Homebrew/downloads/3563d549219575d9d8468dc9b9e4d853c7fdc2b7794e4286440855b2f83e34af--nsolid-v4.3.0-fermium-darwin-x64.tar.gz
==> Downloading https://s3-us-west-2.amazonaws.com/nodesource-public-downloads/4.1.0/artifacts/bundles/nsolid-bundle-v4
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: cee8be458147d85d8ea5334402fb399086c4ae722b8e00feb991891578533462
  Actual: 3619fe702d8336758f8e50e03e22fc9f768ab799cef549544c4fbbbddd09317e
    File: /Users/ben1231/Library/Caches/Homebrew/downloads/c2ba63d0fc4f3835e8206045d47a51cd8eb19371c86020715ec6e6a82928eda6--nsolid-console-v4.1.0-darwin-x64.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by Gioyik** [comment]
hey @gaje,

Yes, something is wrong with the installation, we are going to give it a check and get back to you soon.

Thanks for the report.

**Comment by jSherz** [comment]
Hey @Gioyik, do you have any updates on this? I'm getting the same checksum issue as OP.

**Comment by Gioyik** [comment]
hey, I have news, for some reason the checksums mixed and we have scheduled a fix for this in next week's release. We are looking into modifying our formulas to let per version installations in case this happens again. for now, you can still install using the installer: https://downloads.nodesource.com/#mac

I'll be back here when the release it's published, but should be out early next week. Thanks

**Comment by Gioyik** [comment]
@gaje and @jSherz, brew is working correctly, you can use it again without problem.

Feel free to open a new ticket if this continues to be a problem, thanks
